server:
 port: 80
 servlet:
  context-path: /mood
  session:
   timeout: 3600
  encoding:
   charset: UTF-8
spring:
 servlet:
  multipart:
   maxFileSize: 10MB
   maxRequestSize: 20MB
 profiles:
  active: prod
logging:
 level:
  root: info
  #jdbc.sqlonly: debug
 file:
  name: "moodlogin.log"
#  path: ""
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] %clr([%X{traceId:-},%X{spanId:-}]) [${PID:-}] --- [%10thread] %clr(%logger{36}) -> %msg %n"
 logback:
  rollingpolicy:
   file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
management:
 endpoints:
#  access:
#   default: none
  web:
   base-path: /app-metric
   exposure:
    include: "*"
    exclude: "caches-cache,caches,info,loggers,configprops,env,beans,conditions,configprops-prefix,heapdump,threaddump,sbom-id,sbom,scheduledtasks,mappings"
# endpoint:
#  loggers:
#   access: read-only

---
# MySQL DB 정보
spring:
 config:
  activate:
   on-profile: local
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/moodtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
  #url: jdbc:log4jdbc:mysql://127.0.0.1:3306/moodtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  username: 
  password: 
  configuration:
   maximum-pool-size: 30

---
# MySQL DB 정보
spring:
 config:
  activate:
   on-profile: prod
 datasource:
  url: jdbc:mysql://new-moodtracker.c9qiamm62bch.ap-northeast-2.rds.amazonaws.com/moodtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: 
  password: 
  configuration:
   maximum-pool-size: 30
