server:
 port: 80
 servlet:
  context-path: /mood
  encoding:
   charset: UTF-8
   
spring:
 datasource:
  url: jdbc:oracle:orcl:@localhost:1521:XE
  driver-class-name: oracle.jdbc.driver.OracleDriver
  username: system
  password: admin
  