server:
 port: 80
 servlet:
  context-path: /mood
  encoding:
   charset: UTF-8
spring:
 servlet:
  multipart:
   maxFileSize: 10MB
   maxRequestSize: 20MB
 profiles:
  active: prod
logging:
 level:
  root: info
#  sql: "org.springframework.jdbc.core"
#  kr.co.moodtracker: debug
 file:
  name: "moodlogin.log"
#  path: ""
 pattern:
  console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%5p] %clr([%X{traceId:-},%X{spanId:-}]) [${PID:-}] --- [%10thread] %clr(%logger{36}) -> %msg %n"
 logback:
  rollingpolicy:
   file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.zip"
  
---
# MySQL DB 정보
spring:
 config:
  activate:
   on-profile: local
 datasource:
  url: jdbc:mysql://127.0.0.1:3306/moodtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: 
  password: 

---
# MySQL DB 정보
spring:
 config:
  activate:
   on-profile: prod
 datasource:
  url: jdbc:mysql://new-moodtracker.c9qiamm62bch.ap-northeast-2.rds.amazonaws.com/moodtracker?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: 
  password: 
